# Numpy

- NumPy is a python library
- it is used for working with arrays
- it is short for "Numerical Python"
- it is used for computation and processing of single and multi dimensional arrays of elements
- smaller memory consumption and better runtime behavior

In [3]:
# to instal the library
# pip install numpy
import numpy

In [5]:
#basic operations
#np is an alias here
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [8]:
a = np.array([1,2,3] , dtype = float)
print(a)

[1. 2. 3.]


In [14]:
a = np.array([1,2,3] , dtype = str)
print(a)

['1' '2' '3']


In [20]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
len(b)

2

In [27]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [28]:
len(c)

1

In [24]:
#get the dimensions of the array
a.ndim

1

In [25]:
b.ndim

2

In [29]:
c.ndim

3

In [30]:
a = np.array([[1,2,3]])

In [31]:
a

array([[1, 2, 3]])

In [32]:
#get shape of a numpy array
a.shape

(1, 3)

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b.shape

(2, 3)

In [35]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
c.shape

(1, 3, 3)

In [37]:
a.dtype

dtype('int64')

In [38]:
#accessing or changing specific elements,rows and columns
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [39]:
a.ndim

2

In [40]:
a.shape

(2, 7)

In [41]:
a[0,3]

np.int64(4)

In [42]:
a[1,0]

np.int64(8)

In [43]:
#get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
#get a specific column from a numpy array
a[:,1]

array([2, 9])

In [46]:
a[1,3] = 40
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 40 12 13 14]]


## Zeros/Ones method in numpy

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones((2,5),dtype = 'int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [52]:
np.full((3,3),50,dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [53]:
np.full((3,3),2,dtype='int32')

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [55]:
np.random.rand(4,4) #random number from 0 to 1 here it is float

array([[0.43493381, 0.29077886, 0.99396916, 0.65339328],
       [0.86976552, 0.14348565, 0.00520758, 0.21024837],
       [0.93255218, 0.50531981, 0.63734497, 0.03319643],
       [0.60646811, 0.71421131, 0.35205331, 0.28649325]])

In [58]:
np.random.randint(size=(2,2)) 
#random number from 0 to 1 here it is int but i have to do it like in the next cell

TypeError: randint() takes at least 1 positional argument (0 given)

In [60]:
np.random.randint(-4,1, size=(3,3))

array([[-3, -1,  0],
       [-2,  0, -2],
       [ 0, -4,  0]], dtype=int32)

In [61]:
np.identity(5) #makes an identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# question 1
extract the first 3 rows from the last 5 columns in a given 2d numpy array

In [62]:
a = np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [63]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [67]:
print(a[0,1:])
print(a[1,1:])
print(a[2,1:])

[2 3 4 5 6]
[20 30 40 50 60]
[12 12 12 12 12]


In [68]:
a[:3 , -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

#question 2 
given a positive number n greater than 2 create a numpy array of size (n*n)
with all zeros and ones such that the ones make a shape of a + sign
input 1: 
3
op:

[[0,1,0]

 [1,1,1]
 
 [0,1,0]]

In [71]:
n = 5

In [72]:
z = np.zeros((n,n), dtype='int32')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [77]:
z[:,n//2]=1
z[n//2,:]=1
z

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int32)